server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        data:
          rest: debug

spring:
  application:
    name: insight

  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: jdbc:postgresql://${DB_HOST}/${DB_DATABASE}?stringtype=unspecified

  web:
    error:
      include-message: always
      include-binding-errors: always

  jackson:
    time-zone: UTC
    mapper:
      "[ACCEPT_CASE_INSENSITIVE_ENUMS]": true

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers:
      - ${KAFKA_HOST}

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: edu.raijin.commons.infrastructure.adapter.messaging.event.*

security:
  rsa:
    public-key: classpath:certs/public-key.pem

kafka:
  topics:
    project-commands:
      topic: project-commands
      properties: \
        spring.json.value.default.type=edu.raijin.commons.infrastructure.adapter.messaging.event.scrum.ProjectEvent,\
        enable.auto.commit=false\
        auto.offset.reset=earliest

    sprint-commands:
      topic: sprint-commands
      properties: \
        spring.json.value.default.type=edu.raijin.commons.infrastructure.adapter.messaging.event.scrum.SprintEvent,\
        enable.auto.commit=false\
        auto.offset.reset=earliest

    story-commands:
      topic: story-commands
      properties: \
        spring.json.value.default.type=edu.raijin.commons.infrastructure.adapter.messaging.event.scrum.StoryEvent,\
        enable.auto.commit=false\
        auto.offset.reset=earliest

    user-commands:
      topic: user-commands
      properties: \
        spring.json.value.default.type=edu.raijin.commons.infrastructure.adapter.messaging.event.identity.UserEvent,\
        enable.auto.commit=false\
        auto.offset.reset=earliest

    member-commands:
      topic: member-commands
      properties: \
        spring.json.value.default.type=edu.raijin.commons.infrastructure.adapter.messaging.event.identity.UserEvent,\
        enable.auto.commit=false\
        auto.offset.reset=earliest
